FROM haproxy:3.0-alpine
LABEL MAINTAINER="Miguel Salinas Gancedo <masalinas.gancedo@gmail.com>"

# defaults for the variables used in haproxy.cfg
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
